### ISSUE TITLE
求大神解答，万分感谢

### ISSUE THREAD

**Issue by rankerui** [HaoliangZhou/Dual-ATME#2]
我下载了项目并运行显示没有result文件也没有文件下的txt所以我补充了如果没有文件就创建文件的代码接着报错D:\Dual-ATME-master\venv\Scripts\python.exe D:\Dual-ATME-master\ModelTrain_MERoI_flow_3ls_cde2019.py 
PyTorch Version:  2.2.2+cpu
Torchvision Version:  0.17.2+cpu
False
Subject Name: 006
---------------------------
data\MEGC2019\v_cde_flow\006_train.txt
	Creating deep model....
	Epoch 0/59
	----------
Traceback (most recent call last):
  File "D:\Dual-ATME-master\ModelTrain_MERoI_flow_3ls_cde2019.py", line 316, in <module>
    main()
  File "D:\Dual-ATME-master\ModelTrain_MERoI_flow_3ls_cde2019.py", line 224, in main
    model_ft = train_model(model_ft, dataloader_train, cosine_sim, criterion, optimizer_ft, device, num_epochs=num_epochs)
  File "D:\Dual-ATME-master\ModelTrain_MERoI_flow_3ls_cde2019.py", line 50, in train_model
    for j, samples in enumerate(dataloaders):
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\_utils.py", line 722, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Dual-ATME-master\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Dual-ATME-master\Datasets.py", line 54, in __getitem__
    img = Image.open("".join(self.imgPath[idx]), 'r').convert('RGB')
  File "D:\Dual-ATME-master\venv\lib\site-packages\PIL\Image.py", line 3277, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\home\\zhouhl\\Documents\\data\\samm\\flow\\033_033_2_2_033_2149-033_2117_flow.png'

这里不知道要怎么修改了，没有找到这个文件，看readme也没有提到，球球大神教我一下，非常感谢

**Comment by HaoliangZhou** [comment]
请关注这一行的报错：“FileNotFoundError: [Errno 2] No such file or directory: 'D:\home\zhouhl\Documents\data\samm\flow\033_033_2_2_033_2149-033_2117_flow.png'”
因为这个路径是我的数据路径，并非你的，所以你需要在我提供的txt文件中，将数据集路径替换成你自己的

**Comment by HaoliangZhou** [comment]
此外，请关注我的readme中的数据准备过程，你需要按照我的范例 有68个被试（megc2019）的txt文件，每个文件里是对应loso验证方式下的图片数据路径，这样以后，模型就会按照subject.txt的顺序，按照loso的方式依次进行训练和测试。

**Comment by lijiayan0602** [comment]
> 另外，请关注我的readme中的数据准备过程，你需要按照我的范例有68个被试（megc2019）的txt文件，每个文件里都是对应验证方式下的图片数据路径，这样以后，模型就会按照subject.txt的顺序，按照loso的方式依次进行训练和测试。

你好，作者，我是按照readme中的数据进行准备，但我不知道图片数据应该放在哪里，看起来好像光流图文件应该给要放在data/MEGC2019里面，可以给我能提供更多你数据存放的位置嘛，万分感谢！
